# Release Template
name-template: "v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Changes

  $CHANGES

# Change Template
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# Categories
categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ðŸ§° Maintenance"
    label: "chore"

# Auto-Labeler
autolabeler:
  - label: "chore"
    files:
      - "*.md"
      - "*.cmake"
      - "CMakeLists.txt"
      - ".gitignore"
      - ".clang-format"
      - ".cmake-format"
    branch:
      - '/docs{0,1}\/.+/'
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    body:
      - "/JIRA-[0-9]{1,4}/"

# Exclude Labels
exclude-labels:
  - "skip-changelog"

# Version Resolver
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
