name: CI

on:
  push:
    paths-ignore:
      - docs/**
      - cmake/**
      - .vscode/**
      - README.md

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        target: [win32, x64, arm64]
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          # Fetch all to make git describe work correctly
          fetch-depth: 0

      - name: Setup CMake
        run: cmake -B build -A ${{matrix.target}} -D Binding_Java=ON

      - name: Build
        run: cmake --build build --config Release --target ALL_BUILD && tree

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: cmake --build build --config Release --target package

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
         generate_release_notes: true

         # Publish Packed files
         files: build/pack/*.zip,build/pack/*.sha1
         fail_on_unmatched_files: true
